# Generated by Django 4.1.4 on 2022-12-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logmessage',
            old_name='message',
            new_name='title',
        ),
    ]
