# Generated by Django 4.1.4 on 2022-12-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0003_logmessage_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='age_rating',
            field=models.CharField(default='Input Age Rating', max_length=30),
        ),
    ]
