# Generated by Django 4.1.4 on 2022-12-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0005_logmessage_description_logmessage_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='age_rating',
            field=models.CharField(default='', max_length=30),
        ),
    ]
