# Generated by Django 4.1.4 on 2022-12-18 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0006_alter_logmessage_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
