# Generated by Django 4.1.4 on 2022-12-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaManager', '0008_alter_logmessage_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='description',
            field=models.CharField(default='', max_length=350),
        ),
    ]
